add_newline = false

format = """\
[](#5e81ac)\
$os\
[](bg:#81a1c1 fg:#5e81ac)\
$directory\
[ ](bg:#88c0d0 fg:#81a1c1)\
$git_branch\
[ ](fg:#88c0d0)\
$fill\
$cmd_duration\
$time\
[\n]()\
$character\
"""

[directory]
format = "[ \uf07c $path ]($style)"
style = "fg:#2e3440 bg:#81a1c1"
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#2e3440 bg:#88c0d0"
always_show_remote = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5e81ac fg:#2e3440"
format = "[ 󱑍 $time ]($style)"

[os]
style = "fg:#2e3440 bg:#5e81ac"
disabled = false

[os.symbols]
Macos = " "

[cmd_duration]
min_time = 0
style = "fg:#2e3440 bg:#81a1c1"
format = "[ $duration ]($style)"

[fill]
symbol = " "
