#############################################################
# Homebrew Taps                                             #
#############################################################

tap "jesseduffield/lazygit"

#############################################################
# Command Line                                              #
#############################################################

# CLI Essentials
brew "awscli"
brew "bat"
brew "bat-extras"
brew "coreutils"
brew "dockutil"
brew "eza"
brew "fd"
brew "fzf"
brew "fortune"
brew "gh"
brew "git"
brew "grep"
brew "less"
brew "mas"
brew "neovim"
brew "ranger"
brew "starship"
brew "thefuck"
brew "tlrc"
brew "tmux"
brew "trash-cli"
brew "wget"
brew "xdg-ninja"
brew "zoxide"
brew "zsh"

# CLI Development Suits
brew "git-delta"
brew "lazydocker"
brew "lazygit"

#############################################################
# Software Development                                      #
#############################################################

# Development Langs, Compilers, Package Managers and SDKs
brew "composer"
brew "n"
brew "node"
brew "npm"
brew "php"

# EOF
