# Add Locations to $path Array
typeset -U path

path=(
  "$N_PREFIX/bin"
  $path
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
)

source <(fzf --zsh)

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.completions"
source "$HOME/.shell/.keys"

bindkey '^[[A' history-substring-search-up
bindkey '^[[A' history-substring-search-down

source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load
