# Options
cask_args appdir: '~/Applications', require_sha: true

#############################################################
# Command Line                                              #
#############################################################

# CLI Essentials
brew 'bat'
brew 'bat-extras'
brew 'coreutils'
brew 'dockutil'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'fortune'
brew 'gh'
brew 'jq'
brew 'git'
brew 'grep'
brew 'less'
brew 'mas'
brew 'neovim'
brew 'ranger'
brew 'starship'
brew 'terminal-notifier'
brew 'thefuck'
brew 'tlrc'
brew 'tmux'
brew 'trash-cli'
brew 'wget'
brew 'xdg-ninja'
brew 'zoxide'
brew 'zsh'

# CLI Development Suits
brew 'git-delta'

# Security Tools
brew 'gnupg'
brew 'pinentry-mac'

#############################################################
# Software Development                                      #
#############################################################

# Development Langs, Compilers, Package Managers and SDKs
brew 'composer'
brew 'node'
brew 'npm'
brew 'php'

#############################################################
# Software Development                                      #
#############################################################

# Development Apps
cask 'gitkraken'
cask 'insomnia'
cask 'helo'
cask 'herd'
cask 'ray'
cask 'tableplus'
cask 'tinkerwell'
cask 'visual-studio-code'

#############################################################
# Desktop Applications                                      #
#############################################################

# Creativity
cask 'audacity'

# Personal Applications
cask '1password'
cask '1password-cli'
cask 'cleanmymac'
cask 'cleanshot'
cask 'figma'
cask 'hazel'
cask 'nordvpn'
cask 'powerphotos'
cask 'readdle-spark'
cask 'synology-drive'
cask 'zoom'

# Browsers
cask 'arc'
cask 'firefox'

# Chat Applications
cask 'discord'
cask 'slack'

# Productivity
cask 'notion'
cask 'time-out'

#############################################################
# Content Creation                                          #
#############################################################

# Video
cask 'ecamm-live'

# Podcasting
cask 'forecast'

# Other
cask 'elgato-camera-hub'
cask 'elgato-control-center'
cask 'elgato-stream-deck'

#############################################################
# MacOS-Specific Stuff                                      #
#############################################################

# Fonts
cask 'font-jetbrains-mono-nerd-font'
cask 'font-meslo-lg-nerd-font'
cask 'font-space-mono-nerd-font'
cask 'font-maple-mono'

# Mac OS Mods and Improvements
cask 'alt-tab'
cask 'bartender'
brew 'blacktop/tap/lporg'
cask 'raycast', args: { require_sha: false }
cask 'the-unarchiver'

# Mac App Store
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Xcode', id: 497799835

#############################################################
# VS Code Extensions                                        #
#############################################################

vscode 'adrianwilczynski.alpine-js-intellisense'
vscode 'adpyke.codesnap'
vscode 'ahinkle.laravel-model-snippets'
vscode 'amiralizadeh9480.laravel-extra-intellisense'
vscode 'arcticicestudio.nord-visual-studio-code'
vscode 'austenc.laravel-blade-spacer'
vscode 'bmewburn.vscode-intelephense-client'
vscode 'bradlc.vscode-tailwindcss'
vscode 'calebporzio.better-phpunit'
vscode 'calebporzio.better-keybindings'
vscode 'calebporzio.simple-project-switcher'
vscode 'chouzz.vscode-better-align'
vscode 'cierra.livewire-vscode'
vscode 'codingyu.laravel-goto-view'
vscode 'dansysanalyst.pest-snippets'
vscode 'dbaeumer.vscode-eslint'
vscode 'EditorConfig.EditorConfig'
vscode 'esbenp.prettier-vscode'
vscode 'formulahendry.auto-close-tag'
vscode 'formulahendry.auto-rename-tag'
vscode 'jaguadoromero.vscode-php-create-class'
vscode 'junstyle.php-cs-fixer'
vscode 'kamikillerto.vscode-colorize'
vscode 'laravel.vscode-laravel'
vscode 'lennardv.livewire-goto-updated'
vscode 'm1guelpf.better-pest'
vscode 'mehedidracula.php-constructor'
vscode 'mehedidracula.php-namespace-resolver'
vscode 'mikestead.dotenv'
vscode 'mrmlnc.vscode-duplicate'
vscode 'neilbrayfield.php-docblocker'
vscode 'onecentlin.laravel-blade'
vscode 'onecentlin.laravel5-snippets'
vscode 'open-southeners.laravel-pint'
vscode 'patbenatar.advanced-new-file'
vscode 'PKief.material-icon-theme'
vscode 'rebornix.toggle'
vscode 'ryannaddy.laravel-artisan'
vscode 'shufo.vscode-blade-formatter'
vscode 'sleistner.vscode-fileutils'
vscode 'stillat-llc.vscode-antlers'
vscode 'stivo.tailwind-fold'
vscode 'vilicvane.sensitive-replace'
vscode 'wmaurer.change-case'
vscode 'xdebug.php-debug'

# EOF
